### ISSUE TITLE
Add Proper Style to Source Codes

### ISSUE THREAD

**Issue by hkakutalua** [Henry-Keys/portfolio-and-blog#11]
It'd be a good idea to prettify source code in blog posts, as of now they're pretty bland.
![image](https://user-images.githubusercontent.com/3662164/93610074-81836680-f9c4-11ea-89fb-b1c1aa40344a.png)

We should also limit the width of source code boxes, as they're overflowing blog post content box:
![image](https://user-images.githubusercontent.com/3662164/93610327-d45d1e00-f9c4-11ea-85a8-0496da8a2d96.png)

**Comment by acidiney** [comment]
I was already to report this.

Checkout this links to help us improve this

https://github.com/PrismJS/prism
https://highlightjs.org/

**Comment by hkakutalua** [comment]
Will do.
Thanks @acidiney

**Comment by hkakutalua** [comment]
Fixed in https://github.com/Henry-Keys/portfolio-and-blog/pull/20
