### ISSUE TITLE
Evento de rolagem smooth

### ISSUE THREAD

**Issue by acidiney** [Henry-Keys/portfolio-and-blog#12]
O smooth permite que o usuário tenha uma experiência de rolagem mais agradável sem a quebra de visual no site de sair de um ponto para o outro como se fosse teletransporte ( Quando clicas num link para navegação interna numa One Page ).

O Smooth é um evento de transição dos mais básicos que existe, mais que com certeza faz muita diferença, você consegue esse resultado usando CSS ou javascript.

Nota: Se fores usar css deves saber que alguns browsers mais antigos não têm suporte. tens que um polyfill... se fores fazer com JS é mais tranquilo.

Caso querias testar o evento.

```css
html {
  scroll-behavior: smooth;
}
```

Referência:
- https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior

**Comment by hkakutalua** [comment]
@acidiney 

Nem sabia que era tao facil assim. Vou alterar ja ja.
Mas caso queira contribuir, sinta-se a vontade se quiser mandar um pull request.

O ficheiro CSS "master" é o **style.css**.

**Comment by acidiney** [comment]
Okay, estou a ver que já estas a criar as issues que estava a para criar... então vou ver se comento alguma coisa importante nelas kkkk
