### ISSUE TITLE
Limit Images Size Per Media Device

### ISSUE THREAD

**Issue by hkakutalua** [Henry-Keys/portfolio-and-blog#13]
We should limit images width and height per media device.
Some images end up overflowing a post content box by being too large.

![image](https://user-images.githubusercontent.com/3662164/93610577-24d47b80-f9c5-11ea-9b49-d22ec3a7c0bf.png)

**Comment by acidiney** [comment]
Here you can simple, tel to image consume the box size... When you create an element and add to him a value of size, all siblings inheart this value... except images.... but if you put an `width: 100%`... Images will respect and will ajust by size of container

**Comment by hkakutalua** [comment]
> 
> 
> Here you can simple, tel to image consume the box size... When you create an element and add to him a value of size, all siblings inheart this value... except images.... but if you put an `width: 100%`... Images will respect and will ajust by size of container

Life savior as always
